name: Make a PR

on:
  workflow_dispatch:

jobs:
  work:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Hello
        run: |
          echo Hello, world! >> README.md
          git checkout -b something
          git add README.md
          git -c user.name=example -c user.email=example@example.com commit -m 'Hello'
          (
          echo '```'
          git show HEAD
          echo
          echo '```'
          ) >> "$GITHUB_STEP_SUMMARY"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
